[package]
name = "mli-ndarray"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2024"

[dependencies]
mli = { path = "../mli", version = "0.11.0" }
ndarray = "0.15.3"
itertools = "0.10.1"
num-traits = "0.2.14"
